package com.freund.tabletop_assistant.model.castable;

public enum CastableType {
    ACID_ARROW("Acid Arrow"),
    ACID_SPLASH("Acid Splash"),
    AID("Aid"),
    ALARM("Alarm"),
    ALTER_SELF("Alter Self"),
    ANIMAL_FRIENDSHIP("Animal Friendship"),
    ANIMAL_MESSENGER("Animal Messenger"),
    ANIMAL_SHAPES("Animal Shapes"),
    ANIMATE_DEAD("Animate Dead"),
    ANIMATE_OBJECTS("Animate Objects"),
    ANTILIFE_SHELL("Antilife Shell"),
    ANTIMAGIC_FIELD("Antimagic Field"),
    ANTIPATHY_SYMPATHY("Antipathy/Sympathy"),
    ARCANE_EYE("Arcane Eye"),
    ARCANE_HAND("Arcane Hand"),
    ARCANE_LOCK("Arcane Lock"),
    ARCANE_SWORD("Arcane Sword"),
    ARCANISTS_MAGIC_AURA("Arcanist's Magic Aura"),
    ASTRAL_PROJECTION("Astral Projection"),
    AUGURY("Augury"),
    AWAKEN("Awaken"),
    BANE("Bane"),
    BANISHMENT("Banishment"),
    BARKSKIN("Barkskin"),
    BEACON_OF_HOPE("Beacon of Hope"),
    BESTOW_CURSE("Bestow Curse"),
    BLACK_TENTACLES("Black Tentacles"),
    BLADE_BARRIER("Blade Barrier"),
    BLESS("Bless"),
    BLIGHT("Blight"),
    BLINDNESS_DEAFNESS("Blindness/Deafness"),
    BLINK("Blink"),
    BLUR("Blur"),
    BRANDING_SMITE("Branding Smite"),
    BURNING_HANDS("Burning Hands"),
    CALL_LIGHTNING("Call Lightning"),
    CALM_EMOTIONS("Calm Emotions"),
    CHAIN_LIGHTNING("Chain Lightning"),
    CHARM_PERSON("Charm Person"),
    CHILL_TOUCH("Chill Touch"),
    CIRCLE_OF_DEATH("Circle of Death"),
    CLAIRVOYANCE("Clairvoyance"),
    CLONE("Clone"),
    CLOUDKILL("Cloudkill"),
    COLOR_SPRAY("Color Spray"),
    COMMAND("Command"),
    COMMUNE("Commune"),
    COMMUNE_WITH_NATURE("Commune With Nature"),
    COMPREHEND_LANGUAGES("Comprehend Languages"),
    COMPULSION("Compulsion"),
    CONE_OF_COLD("Cone of Cold"),
    CONFUSION("Confusion"),
    CONJURE_ANIMALS("Conjure Animals"),
    CONJURE_CELESTIAL("Conjure Celestial"),
    CONJURE_ELEMENTAL("Conjure Elemental"),
    CONJURE_FEY("Conjure Fey"),
    CONJURE_MINOR_ELEMENTALS("Conjure Minor Elementals"),
    CONJURE_WOODLAND_BEINGS("Conjure Woodland Beings"),
    CONTACT_OTHER_PLANE("Contact Other Plane"),
    CONTAGION("Contagion"),
    CONTINGENCY("Contingency"),
    CONTINUAL_FLAME("Continual Flame"),
    CONTROL_WATER("Control Water"),
    CONTROL_WEATHER("Control Weather"),
    COUNTERSPELL("Counterspell"),
    CREATE_FOOD_AND_WATER("Create Food and Water"),
    CREATE_UNDEAD("Create Undead"),
    CREATE_OR_DESTROY_WATER("Create or Destroy Water"),
    CREATION("Creation"),
    CURE_WOUNDS("Cure Wounds"),
    DANCING_LIGHTS("Dancing Lights"),
    DARKNESS("Darkness"),
    DARKVISION("Darkvision"),
    DAYLIGHT("Daylight"),
    DEATH_WARD("Death Ward"),
    DELAYED_BLAST_FIREBALL("Delayed Blast Fireball"),
    DEMIPLANE("Demiplane"),
    DETECT_EVIL_AND_GOOD("Detect Evil and Good"),
    DETECT_MAGIC("Detect Magic"),
    DETECT_POISON_AND_DISEASE("Detect Poison and Disease"),
    DETECT_THOUGHTS("Detect Thoughts"),
    DIMENSION_DOOR("Dimension Door"),
    DISGUISE_SELF("Disguise Self"),
    DISINTEGRATE("Disintegrate"),
    DISPEL_EVIL_AND_GOOD("Dispel Evil and Good"),
    DISPEL_MAGIC("Dispel Magic"),
    DIVINATION("Divination"),
    DIVINE_FAVOR("Divine Favor"),
    DIVINE_WORD("Divine Word"),
    DOMINATE_BEAST("Dominate Beast"),
    DOMINATE_MONSTER("Dominate Monster"),
    DOMINATE_PERSON("Dominate Person"),
    DREAM("Dream"),
    DRUIDCRAFT("Druidcraft"),
    EARTHQUAKE("Earthquake"),
    ELDRITCH_BLAST("Eldritch Blast"),
    ENHANCE_ABILITY("Enhance Ability"),
    ENLARGE_REDUCE("Enlarge/Reduce"),
    ENTANGLE("Entangle"),
    ENTHRALL("Enthrall"),
    ETHEREALNESS("Etherealness"),
    EXPEDITIOUS_RETREAT("Expeditious Retreat"),
    EYEBITE("Eyebite"),
    FABRICATE("Fabricate"),
    FAERIE_FIRE("Faerie Fire"),
    FAITHFUL_HOUND("Faithful Hound"),
    FALSE_LIFE("False Life"),
    FEAR("Fear"),
    FEATHER_FALL("Feather Fall"),
    FEEBLEMIND("Feeblemind"),
    FIND_FAMILIAR("Find Familiar"),
    FIND_STEED("Find Steed"),
    FIND_TRAPS("Find Traps"),
    FIND_THE_PATH("Find the Path"),
    FINGER_OF_DEATH("Finger of Death"),
    FIRE_BOLT("Fire Bolt"),
    FIRE_SHIELD("Fire Shield"),
    FIRE_STORM("Fire Storm"),
    FIREBALL("Fireball"),
    FLAME_BLADE("Flame Blade"),
    FLAME_STRIKE("Flame Strike"),
    FLAMING_SPHERE("Flaming Sphere"),
    FLESH_TO_STONE("Flesh to Stone"),
    FLOATING_DISK("Floating Disk"),
    FLY("Fly"),
    FOG_CLOUD("Fog Cloud"),
    FORBIDDANCE("Forbiddance"),
    FORCECAGE("Forcecage"),
    FORESIGHT("Foresight"),
    FREEDOM_OF_MOVEMENT("Freedom of Movement"),
    FREEZING_SPHERE("Freezing Sphere"),
    GASEOUS_FORM("Gaseous Form"),
    GATE("Gate"),
    GEAS("Geas"),
    GENTLE_REPOSE("Gentle Repose"),
    GIANT_INSECT("Giant Insect"),
    GLIBNESS("Glibness"),
    GLOBE_OF_INVULNERABILITY("Globe of Invulnerability"),
    GLYPH_OF_WARDING("Glyph of Warding"),
    GOODBERRY("Goodberry"),
    GREASE("Grease"),
    GREATER_INVISIBILITY("Greater Invisibility"),
    GREATER_RESTORATION("Greater Restoration"),
    GUARDIAN_OF_FAITH("Guardian of Faith"),
    GUARDS_AND_WARDS("Guards and Wards"),
    GUIDANCE("Guidance"),
    GUIDING_BOLT("Guiding Bolt"),
    GUST_OF_WIND("Gust of Wind"),
    HALLOW("Hallow"),
    HALLUCINATORY_TERRAIN("Hallucinatory Terrain"),
    HARM("Harm"),
    HASTE("Haste"),
    HEAL("Heal"),
    HEALING_WORD("Healing Word"),
    HEAT_METAL("Heat Metal"),
    HELLISH_REBUKE("Hellish Rebuke"),
    HEROES_FEAST("Heroes' Feast"),
    HEROISM("Heroism"),
    HIDEOUS_LAUGHTER("Hideous Laughter"),
    HOLD_MONSTER("Hold Monster"),
    HOLD_PERSON("Hold Person"),
    HOLY_AURA("Holy Aura"),
    HUNTERS_MARK("Hunter's Mark"),
    HYPNOTIC_PATTERN("Hypnotic Pattern"),
    ICE_STORM("Ice Storm"),
    IDENTIFY("Identify"),
    ILLUSORY_SCRIPT("Illusory Script"),
    IMPRISONMENT("Imprisonment"),
    INCENDIARY_CLOUD("Incendiary Cloud"),
    INFLICT_WOUNDS("Inflict Wounds"),
    INSECT_PLAGUE("Insect Plague"),
    INSTANT_SUMMONS("Instant Summons"),
    INVISIBILITY("Invisibility"),
    IRRESISTIBLE_DANCE("Irresistible Dance"),
    JUMP("Jump"),
    KNOCK("Knock"),
    LEGEND_LORE("Legend Lore"),
    LESSER_RESTORATION("Lesser Restoration"),
    LEVITATE("Levitate"),
    LIGHT("Light"),
    LIGHTNING_BOLT("Lightning Bolt"),
    LOCATE_ANIMALS_OR_PLANTS("Locate Animals or Plants"),
    LOCATE_CREATURE("Locate Creature"),
    LOCATE_OBJECT("Locate Object"),
    LONGSTRIDER("Longstrider"),
    MAGE_ARMOR("Mage Armor"),
    MAGE_HAND("Mage Hand"),
    MAGIC_CIRCLE("Magic Circle"),
    MAGIC_JAR("Magic Jar"),
    MAGIC_MISSILE("Magic Missile"),
    MAGIC_MOUTH("Magic Mouth"),
    MAGIC_WEAPON("Magic Weapon"),
    MAGNIFICENT_MANSION("Magnificent Mansion"),
    MAJOR_IMAGE("Major Image"),
    MASS_CURE_WOUNDS("Mass Cure Wounds"),
    MASS_HEAL("Mass Heal"),
    MASS_HEALING_WORD("Mass Healing Word"),
    MASS_SUGGESTION("Mass Suggestion"),
    MAZE("Maze"),
    MELD_INTO_STONE("Meld Into Stone"),
    MENDING("Mending"),
    MESSAGE("Message"),
    METEOR_SWARM("Meteor Swarm"),
    MIND_BLANK("Mind Blank"),
    MINOR_ILLUSION("Minor Illusion"),
    MIRAGE_ARCANE("Mirage Arcane"),
    MIRROR_IMAGE("Mirror Image"),
    MISLEAD("Mislead"),
    MISTY_STEP("Misty Step"),
    MODIFY_MEMORY("Modify Memory"),
    MOONBEAM("Moonbeam"),
    MOVE_EARTH("Move Earth"),
    NONDETECTION("Nondetection"),
    PASS_WITHOUT_TRACE("Pass Without Trace"),
    PASSWALL("Passwall"),
    PHANTASMAL_KILLER("Phantasmal Killer"),
    PHANTOM_STEED("Phantom Steed"),
    PLANAR_ALLY("Planar Ally"),
    PLANAR_BINDING("Planar Binding"),
    PLANE_SHIFT("Plane Shift"),
    PLANT_GROWTH("Plant Growth"),
    POISON_SPRAY("Poison Spray"),
    POLYMORPH("Polymorph"),
    POWER_WORD_KILL("Power Word Kill"),
    POWER_WORD_STUN("Power Word Stun"),
    PRAYER_OF_HEALING("Prayer of Healing"),
    PRESTIDIGITATION("Prestidigitation"),
    PRISMATIC_SPRAY("Prismatic Spray"),
    PRISMATIC_WALL("Prismatic Wall"),
    PRIVATE_SANCTUM("Private Sanctum"),
    PRODUCE_FLAME("Produce Flame"),
    PROGRAMMED_ILLUSION("Programmed Illusion"),
    PROJECT_IMAGE("Project Image"),
    PROTECTION_FROM_ENERGY("Protection From Energy"),
    PROTECTION_FROM_EVIL_AND_GOOD("Protection from Evil and Good"),
    PROTECTION_FROM_POISON("Protection from Poison"),
    PURIFY_FOOD_AND_DRINK("Purify Food and Drink"),
    RAISE_DEAD("Raise Dead"),
    RAY_OF_ENFEEBLEMENT("Ray of Enfeeblement"),
    RAY_OF_FROST("Ray of Frost"),
    REGENERATE("Regenerate"),
    REINCARNATE("Reincarnate"),
    REMOVE_CURSE("Remove Curse"),
    RESILIENT_SPHERE("Resilient Sphere"),
    RESISTANCE("Resistance"),
    RESURRECTION("Resurrection"),
    REVERSE_GRAVITY("Reverse Gravity"),
    REVIVIFY("Revivify"),
    ROPE_TRICK("Rope Trick"),
    SACRED_FLAME("Sacred Flame"),
    SANCTUARY("Sanctuary"),
    SCORCHING_RAY("Scorching Ray"),
    SCRYING("Scrying"),
    SECRET_CHEST("Secret Chest"),
    SEE_INVISIBILITY("See Invisibility"),
    SEEMING("Seeming"),
    SENDING("Sending"),
    SEQUESTER("Sequester"),
    SHAPECHANGE("Shapechange"),
    SHATTER("Shatter"),
    SHIELD("Shield"),
    SHIELD_OF_FAITH("Shield of Faith"),
    SHILLELAGH("Shillelagh"),
    SHOCKING_GRASP("Shocking Grasp"),
    SILENCE("Silence"),
    SILENT_IMAGE("Silent Image"),
    SIMULACRUM("Simulacrum"),
    SLEEP("Sleep"),
    SLEET_STORM("Sleet Storm"),
    SLOW("Slow"),
    SPARE_THE_DYING("Spare the Dying"),
    SPEAK_WITH_ANIMALS("Speak with Animals"),
    SPEAK_WITH_DEAD("Speak with Dead"),
    SPEAK_WITH_PLANTS("Speak with Plants"),
    SPIDER_CLIMB("Spider Climb"),
    SPIKE_GROWTH("Spike Growth"),
    SPIRIT_GUARDIANS("Spirit Guardians"),
    SPIRITUAL_WEAPON("Spiritual Weapon"),
    STINKING_CLOUD("Stinking Cloud"),
    STONE_SHAPE("Stone Shape"),
    STONESKIN("Stoneskin"),
    STORM_OF_VENGEANCE("Storm of Vengeance"),
    SUGGESTION("Suggestion"),
    SUNBEAM("Sunbeam"),
    SUNBURST("Sunburst"),
    SYMBOL("Symbol"),
    TELEKINESIS("Telekinesis"),
    TELEPATHIC_BOND("Telepathic Bond"),
    TELEPORT("Teleport"),
    TELEPORTATION_CIRCLE("Teleportation Circle"),
    THAUMATURGY("Thaumaturgy"),
    THUNDERWAVE("Thunderwave"),
    TIME_STOP("Time Stop"),
    TINY_HUT("Tiny Hut"),
    TONGUES("Tongues"),
    TRANSPORT_VIA_PLANTS("Transport via Plants"),
    TREE_STRIDE("Tree Stride"),
    TRUE_POLYMORPH("True Polymorph"),
    TRUE_RESURRECTION("True Resurrection"),
    TRUE_SEEING("True Seeing"),
    TRUE_STRIKE("True Strike"),
    UNSEEN_SERVANT("Unseen Servant"),
    VAMPIRIC_TOUCH("Vampiric Touch"),
    VICIOUS_MOCKERY("Vicious Mockery"),
    WALL_OF_FIRE("Wall of Fire"),
    WALL_OF_FORCE("Wall of Force"),
    WALL_OF_ICE("Wall of Ice"),
    WALL_OF_STONE("Wall of Stone"),
    WALL_OF_THORNS("Wall of Thorns"),
    WARDING_BOND("Warding Bond"),
    WATER_BREATHING("Water Breathing"),
    WATER_WALK("Water Walk"),
    WEB("Web"),
    WEIRD("Weird"),
    WIND_WALK("Wind Walk"),
    WIND_WALL("Wind Wall"),
    WISH("Wish"),
    WORD_OF_RECALL("Word of Recall"),
    ZONE_OF_TRUTH("Zone of Truth");

    public final String CASTABLE_NAME;

    CastableType(String castableName) {
        this.CASTABLE_NAME = castableName;
    }
}
